export const projects = [
  {
    id: "venus",
    name: "Reading Venus",
    category: "PLANETARY INSTRUMENTATION",
    org: "NASA VfOx · DAVINCI / APL deliverables",
    year: "2024",
    role: "Student Lead",
    color: "#edb879",
    rgb: [0.91, 0.57, 0.27],
    title: "A small sensor.\nAn enormous atmosphere.",
    description:
      "In-situ numerical analysis of Venus’s atmosphere for the Oxygen Fugacity Sensor (VfOx), with contributions to instrument design, assembly and testing. Produced deliverables for NASA DAVINCI and the Applied Physics Laboratory.",
    tags: ["Venus atmosphere", "Numerical analysis", "Instrument testing"],
    note: "Cloud bands and an orbiting probe imagine the atmosphere surrounding the sensor work.",
    control: "Atmospheric flow",
    symbol: "VfOx",
    coordinates: "01 / VENUS",
  },
  {
    id: "imaging",
    name: "Seeing the unseen",
    category: "COMPUTATIONAL IMAGING",
    org: "Stanford · Radiological Sciences Laboratory REU",
    year: "2025",
    role: "Research Intern",
    color: "#9ddcdb",
    rgb: [0.31, 0.76, 0.77],
    title: "Less radiation.\nMore information.",
    description:
      "Developed a 2.5D physics-informed diffusion model for sparse-view cone-beam CT reconstruction of spine images. Integrated the Radon transform as a physical forward constraint, and evaluated anatomical fidelity with downstream segmentation.",
    tags: ["Diffusion models", "Radon transform", "Sparse-view CT"],
    note: "A moving scan plane reveals luminous internal structures: an illustration of an inverse problem, not a medical image.",
    control: "Scan frequency",
    symbol: "R[f]",
    coordinates: "02 / TOMOGRAPHY",
    link: "https://drive.google.com/file/d/1dviuzmckyB8s-0lzJKJfOB2dXtAYdcyc/view?usp=sharing",
    linkLabel: "View research poster",
  },
  {
    id: "particles",
    name: "Order from noise",
    category: "GENERATIVE MODELING",
    org: "Johns Hopkins · Research with Dr. Fei Lu",
    year: "2025–",
    role: "Research Assistant",
    color: "#c8b2f2",
    rgb: [0.65, 0.45, 0.95],
    title: "Local interactions.\nGlobal possibilities.",
    description:
      "Formulating patch-based generative models as interacting particle systems to study local constraints and global consistency. Using statistical mechanics and optimal transport to investigate convergence, mode coverage and stable hybrid architectures for medical imaging.",
    tags: [
      "Interacting particles",
      "Optimal transport",
      "Statistical mechanics",
    ],
    note: "A spherical particle field moves between scattered and organized states. The visual is a metaphor for ongoing research.",
    control: "Field coupling",
    symbol: "∇W₂",
    coordinates: "03 / PARTICLE FIELD",
  },
  {
    id: "matter",
    name: "Matter in motion",
    category: "SOFT MATTER & BIOPHYSICS",
    org: "Johns Hopkins · Beller Research Group",
    year: "2024–",
    role: "Undergraduate Research Assistant",
    color: "#b9d591",
    rgb: [0.53, 0.74, 0.31],
    title: "Tiny fluctuations.\nCollective motion.",
    description:
      "Ran Brownian dynamics simulations of active particles and bead-spring chains using Lennard-Jones potentials and Hookean springs. Investigated self-propulsion and diffusion in nematic-shaped particles, with a focus on convergence and stability.",
    tags: ["Brownian dynamics", "Active matter", "Bead-spring chains"],
    note: "Wandering filaments and flowing domains evoke active matter. These are procedural illustrations, not simulation results.",
    control: "Activity",
    symbol: "⟨Δr²⟩",
    coordinates: "04 / ACTIVE MATTER",
    link: "https://drive.google.com/file/d/1Z1x8eYSvfKmizgS9J_TXseVaaQUHejTi/view?usp=sharing",
    linkLabel: "Read research summary",
  },
  {
    id: "moon",
    name: "Backside of the Moon",
    category: "WORLDBUILDING & GAME PHYSICS",
    org: "Independent · Supported by Pava & Engineering",
    year: "2024–",
    role: "Founder",
    color: "#a6c6f6",
    rgb: [0.39, 0.61, 0.95],
    title: "Build a world.\nThen let it surprise you.",
    description:
      "Building an SCP-style roguelike with procedural level generation, game logic, AI behavior and physics integration. Secured funding from the Pava Accelerator and the Engineering Department.",
    tags: ["Procedural worlds", "Game AI", "Physics integration"],
    note: "A wireframe moon with procedural terrain represents a world under construction; it is original artwork, not a game screenshot.",
    control: "Terrain complexity",
    symbol: "SEED",
    coordinates: "05 / PROCEDURAL MOON",
    link: "https://github.com/ZichenFrankFu/Backside_of_the_Moon",
    linkLabel: "Explore the game repository",
  },
];
